# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            str(Aaron1011)
tagline:          The Blog of Aaron1011
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Aaron Hill
  email:          aa1ronham@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
