# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            str(Aaron1011)
tagline:          The Blog of Aaron1011
url:              http://aaron1011.github.io
paginate:         5
baseurl:          /
author:
  name:           Aaron Hill
  email:          aa1ronham@gmail.com


owner:
  name: Aaron Hill
  avatar: ubuntu.jpeg
  bio: "I'm a software developer living in New Hampshire, who works with a variety of languages and technologies"
  email: me@aaron1011.pw
  twitter: AaronThe1011
  github: Aaron1011
  stackexchange: Aaron1011


# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

timezone:    America/New_York
future:      true

excerpt_separator: "\n\n"

disqus_shortname: 'aaron1011'
