# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            str(Aaron1011)
tagline:          The Blog of Aaron1011
url:              http://aaron1011.github.io
paginate:         5
baseurl:          /
author:
  name:           Aaron Hill
  email:          aa1ronham@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

excerpt_separator: "\n\n"

disqus_shortname: 'aaron1011'
